[package]
name = "klotho"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
indicatif = "0.17"
owo-colors = "4.0"
rust-embed = "8"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
dialoguer = "0.11"
regex-lite = "0.1"
